# web-loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: front-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
