name: Mi workflow

on: 
  push:
    branches:
      - main

jobs: 
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: cuadron11/as-laboratorio-8-web
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.TOKEN_GOOGLE_CLOUD }}
          project_id: ${{ secrets.NOMBRE_PROYECTO_CLUSTER }}

      - name: Login to Kubernetes
        uses: simenandre/setup-gke-gcloud-auth-plugin@v1
      - name: Configurar herramienta kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: labo8
          location: europe-west10
      - name: Desplegar objetos Kubernetes
        run: |
          kubectl apply -f k8s/front-web-deployment.yaml
          kubectl apply -f k8s/db-deployment.yaml
          kubectl rollout restart deployment front-web-deployment
          kubectl rollout restart deployment db-deployment
          kubectl apply -f k8s/db-service.yaml
          kubectl apply -f k8s/web-loadbalancer.yaml
